/// <reference lib="deno.ns" />

type CatalogItem = {
  id: string;
  source: "github:choosealicense";
  key: string;
  spdxId: string;
  name: string;
  description?: string;
  sourceUrl: string;
  path: string;
  hash: string;
  permissions: string[];
  conditions: string[];
  limitations: string[];
};

type GeneratedItem = CatalogItem & { body: string; };

const branch = "gh-pages";
const encoder = new TextEncoder();

async function main() {
  const items = await fetchLicenses();

  await Deno.mkdir("data/licenses/github/raw", { recursive: true });
  await Deno.mkdir("src/generated", { recursive: true });

  for (const item of items) {
    await Deno.writeTextFile(item.path, item.body);
  }

  const catalog = items.map(({ body: _body, ...item }) => item);
  await Deno.writeTextFile("data/licenses/catalog.json", `${JSON.stringify(catalog, null, 2)}\n`);
  await Deno.writeTextFile("data/licenses/github/index.json", `${JSON.stringify(catalog, null, 2)}\n`);
  await Deno.writeTextFile(
    "src/generated/licenses.ts",
    `// Generated by deno task sync:licenses. Do not edit by hand.\n\nexport const licenseTemplates = ${
      JSON.stringify(items, null, 2)
    } as const;\n`,
  );

  console.log(`Generated ${items.length} license templates.`);
}

async function fetchLicenses(): Promise<GeneratedItem[]> {
  const treeUrl = `https://api.github.com/repos/github/choosealicense.com/git/trees/${branch}?recursive=1`;
  const response = await fetch(treeUrl, { headers: { "user-agent": "utility-api-sync" } });
  if (!response.ok) throw new Error(`Choose a License tree fetch failed: ${response.status} ${await response.text()}`);

  const data = await response.json() as { tree: Array<{ path: string; type: string; }>; };
  const entries = data.tree.filter((entry) => entry.type === "blob" && /^_licenses\/[^/]+\.txt$/.test(entry.path));
  const items: GeneratedItem[] = [];

  for (const entry of entries) {
    const sourceUrl = `https://raw.githubusercontent.com/github/choosealicense.com/${branch}/${entry.path}`;
    const sourceResponse = await fetch(sourceUrl, { headers: { "user-agent": "utility-api-sync" } });
    if (!sourceResponse.ok) throw new Error(`License fetch failed: ${entry.path}`);

    const raw = await sourceResponse.text();
    const parsed = parseLicense(raw);
    const key = entry.path.split("/").at(-1)!.replace(/\.txt$/i, "");
    const body = parsed.body.trim() + "\n";

    items.push({
      id: parsed.spdxId.toLowerCase(),
      source: "github:choosealicense",
      key,
      spdxId: parsed.spdxId,
      name: parsed.title,
      description: parsed.description,
      sourceUrl,
      path: `data/licenses/github/raw/${key}.txt`,
      hash: await sha256(body),
      permissions: parsed.permissions,
      conditions: parsed.conditions,
      limitations: parsed.limitations,
      body,
    });
  }

  return items.sort((a, b) => a.spdxId.localeCompare(b.spdxId));
}

function parseLicense(raw: string) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error("License file is missing front matter.");

  const frontMatter = match[1];
  return {
    title: scalar(frontMatter, "title") ?? "Unknown license",
    spdxId: scalar(frontMatter, "spdx-id") ?? scalar(frontMatter, "key") ?? "unknown",
    description: scalar(frontMatter, "description"),
    permissions: list(frontMatter, "permissions"),
    conditions: list(frontMatter, "conditions"),
    limitations: list(frontMatter, "limitations"),
    body: match[2],
  };
}

function scalar(frontMatter: string, key: string): string | undefined {
  const match = frontMatter.match(new RegExp(`^${escapeRegExp(key)}:\\s*(.+)$`, "m"));
  return match?.[1]?.trim().replace(/^['"]|['"]$/g, "");
}

function list(frontMatter: string, key: string): string[] {
  const match = frontMatter.match(new RegExp(`^${escapeRegExp(key)}:\\n((?:  - .+\\n?)+)`, "m"));
  if (!match) return [];
  return match[1].split("\n").map((line) => line.trim().replace(/^-\s*/, "")).filter(Boolean);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

async function sha256(value: string): Promise<string> {
  const hash = await crypto.subtle.digest("SHA-256", encoder.encode(value));
  return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

if (import.meta.main) await main();
