type Source = "github" | "toptal";

type CatalogItem = {
  id: string;
  source: Source;
  key: string;
  name: string;
  aliases: string[];
  description?: string;
  path: string;
  hash: string;
};

type GeneratedItem = CatalogItem & { body: string; };

const encoder = new TextEncoder();

async function main() {
  const github = await fetchGitHubTemplates();
  const toptal = await fetchToptalTemplates();
  const items = [...github, ...toptal].sort((a, b) => a.id.localeCompare(b.id));

  await Deno.mkdir("data/ignores/github/raw", { recursive: true });
  await Deno.mkdir("data/ignores/toptal/raw", { recursive: true });
  await Deno.mkdir("src/generated", { recursive: true });

  for (const item of items) {
    const directory = item.path.split("/").slice(0, -1).join("/");
    await Deno.mkdir(directory, { recursive: true });
    await Deno.writeTextFile(item.path, item.body);
  }

  const catalog = items.map(({ body: _body, ...item }) => item);
  const bySource = {
    github: catalog.filter((item) => item.source === "github"),
    toptal: catalog.filter((item) => item.source === "toptal"),
  };

  await Deno.writeTextFile("data/ignores/catalog.json", `${JSON.stringify(catalog, null, 2)}\n`);
  await Deno.writeTextFile("data/ignores/github/index.json", `${JSON.stringify(bySource.github, null, 2)}\n`);
  await Deno.writeTextFile("data/ignores/toptal/index.json", `${JSON.stringify(bySource.toptal, null, 2)}\n`);

  await Deno.writeTextFile(
    "src/generated/ignores.ts",
    `// Generated by deno task sync:ignores. Do not edit by hand.\n\nexport const ignoreTemplates = ${
      JSON.stringify(items, null, 2)
    } as const;\n`,
  );

  console.log(`Generated ${items.length} gitignore templates.`);
}

async function fetchGitHubTemplates(): Promise<GeneratedItem[]> {
  const treeUrl = "https://api.github.com/repos/github/gitignore/git/trees/main?recursive=1";
  const response = await fetch(treeUrl, { headers: { "user-agent": "utility-api-sync" } });
  if (!response.ok) {
    throw new Error(`GitHub tree fetch failed: ${response.status} ${await response.text()}`);
  }

  const data = await response.json() as { tree: Array<{ path: string; type: string; url: string; }>; };
  const entries = data.tree.filter((entry) => entry.type === "blob" && entry.path.endsWith(".gitignore"));
  const items: GeneratedItem[] = [];

  for (const entry of entries) {
    const rawUrl = `https://raw.githubusercontent.com/github/gitignore/main/${entry.path}`;
    const contentResponse = await fetch(rawUrl, { headers: { "user-agent": "utility-api-sync" } });
    if (!contentResponse.ok) {
      throw new Error(`GitHub template fetch failed: ${entry.path}`);
    }

    const body = await contentResponse.text();
    const name = entry.path.split("/").at(-1)!.replace(/\.gitignore$/i, "");
    const key = normalizeKey(entry.path.replace(/\.gitignore$/i, ""));
    const relativeRawPath = `data/ignores/github/raw/${entry.path}`;

    items.push({
      id: `github:${key}`,
      source: "github",
      key,
      name,
      aliases: aliasesFor(name, entry.path),
      path: relativeRawPath,
      hash: await sha256(body),
      body,
    });
  }

  return items;
}

async function fetchToptalTemplates(): Promise<GeneratedItem[]> {
  const response = await fetch("https://www.toptal.com/developers/gitignore/api/list?format=json");
  if (!response.ok) {
    throw new Error(`Toptal fetch failed: ${response.status} ${await response.text()}`);
  }

  const data = await response.json() as Record<
    string,
    { contents: string; key: string; fileName?: string; name?: string; }
  >;
  const items: GeneratedItem[] = [];

  for (const value of Object.values(data)) {
    const key = normalizeKey(value.key);
    const name = value.name ?? value.fileName?.replace(/\.gitignore$/i, "") ?? value.key;
    const body = value.contents;

    items.push({
      id: `toptal:${key}`,
      source: "toptal",
      key,
      name,
      aliases: aliasesFor(name, value.key, value.fileName ?? ""),
      path: `data/ignores/toptal/raw/${key}.gitignore`,
      hash: await sha256(body),
      body,
    });
  }

  return items;
}

function aliasesFor(...values: string[]): string[] {
  const aliases = new Set<string>();
  for (const value of values) {
    const clean = value.replace(/\.gitignore$/i, "").split("/").at(-1) ?? value;
    aliases.add(normalizeKey(clean));
    aliases.add(clean.toLowerCase());
  }
  return [...aliases].filter(Boolean).sort();
}

function normalizeKey(value: string): string {
  return value.replace(/\.gitignore$/i, "").trim().toLowerCase().replace(/\+/g, "plus").replace(/#/g, "sharp").replace(
    /[^a-z0-9]+/g,
    "-",
  ).replace(/^-+|-+$/g, "");
}

async function sha256(value: string): Promise<string> {
  const hash = await crypto.subtle.digest("SHA-256", encoder.encode(value));
  return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

if (import.meta.main) await main();
